apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ece-devops-2022
  labels:
    api: ece-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      api: ece-devops
  template:
    metadata:
      labels:
        api: ece-devops
    spec:
      containers:
        - name: ece-webapp-pl-kilan
          image: pierrolobogo/ece-webapp-pl-kilan
          ports:
            - containerPort: 9000
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: project-devops-service
spec:
  selector:
    api: ece-devops
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30000